services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend1
      - backend
      
    networks:
      - testing1

  frontend1: #Service name
    container_name: frontend1
    image: fc-end-ig:latest
    expose:
      - "80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost > /dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - testing1

  backend:
    container_name: backend
    image: backend-ig:latest
    expose:
      - "8080"
    environment:  
      - MONGO_URL=mongodb://mongo:27017/dd_db
    depends_on:
      - mongo
    command: >
      sh -c "
      until getent hosts mongo;
      do echo 'Waiting for Mongo DNS...';
      sleep 2;
      done;
      node server.js
      "
    networks:
      - testing1


  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - testing1

volumes:
  mongodata:
    driver: local

networks:
  testing1:
    name: testing1
    driver: bridge
